site_name: BirchFlow Docs
site_url: https://github.com/toCase/birchflow
theme:
  name: material
  favicon: 'img/favicon.png'
  language: uk
  logo: 
  font: 
    text: Noto Sans
    code: JetBrains Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: light purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light purple
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - 'BirchFlow': 'index.md'
  - 'Налаштування': 'settings.md'
  - 'Партнери': 'partners.md'
  - 'Контракти': 'contracts.md'
